POST http://localhost:5000/applications/test

// Users
### Register user
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "name": "Abdur Rahim",
    "email": "abdoerrahiem2@gmail.com",
    "password": "12345678"
}

### Send OTP
POST http://localhost:5000/users/otp
Content-Type: application/json

{
    "email": "abdoerrahiem@gmail.com"
}

### Vefiry user
POST http://localhost:5000/users/verify
Content-Type: application/json

{
    "email": "abdoerrahiem@gmail.com",
    "otp": "lfrj4u"
}

### Login user
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "abdoerrahiem2@gmail.com",
    "password": "12345678"
}

### Update name
PUT http://localhost:5000/users/update/name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBiYjE3OTE2MTc1MTdiMDE5YzRjMiIsImlhdCI6MTYyOTUzNzQwNywiZXhwIjoxNjMyMTI5NDA3fQ.57swjteBvhQyEGl0aNI3GS1SHclPOOMOXAUtneX8BwQ

{
    "name": "Abdur Rahim"
}

### Update birthdate
PUT http://localhost:5000/users/update/birthdate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBiYjE3OTE2MTc1MTdiMDE5YzRjMiIsImlhdCI6MTYyOTUzNzQwNywiZXhwIjoxNjMyMTI5NDA3fQ.57swjteBvhQyEGl0aNI3GS1SHclPOOMOXAUtneX8BwQ

{
    "birthdate": "16-12-1998"
}

### Update email
PUT http://localhost:5000/users/update/email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBiYjE3OTE2MTc1MTdiMDE5YzRjMiIsImlhdCI6MTYyOTUzNzQwNywiZXhwIjoxNjMyMTI5NDA3fQ.57swjteBvhQyEGl0aNI3GS1SHclPOOMOXAUtneX8BwQ

{
    "email": "abdoerrahiem@gmail.com"
}

### Update password
PUT http://localhost:5000/users/update/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBiYjE3OTE2MTc1MTdiMDE5YzRjMiIsImlhdCI6MTYyOTUzNzQwNywiZXhwIjoxNjMyMTI5NDA3fQ.57swjteBvhQyEGl0aNI3GS1SHclPOOMOXAUtneX8BwQ

{
    "oldPassword": "abdoerrahiem2",
    "newPassword": "abdoerrahiem"
}

### Update photo
PUT http://localhost:5000/users/update/photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBiYjE3OTE2MTc1MTdiMDE5YzRjMiIsImlhdCI6MTYyOTUzNzQwNywiZXhwIjoxNjMyMTI5NDA3fQ.57swjteBvhQyEGl0aNI3GS1SHclPOOMOXAUtneX8BwQ

{
    "photo": "https://scontent.fpnk3-1.fna.fbcdn.net/v/t1.6435-9/56368677_836555680011041_1338138305639743488_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=09cbfe&_nc_eui2=AeEfkPLAezFgH-sa1iSHcSPUikyRu5ecazaKTJG7l5xrNra_S6LDxXzjV4UCU6iwLUY65oR3uEbSDgzYHMROm9Q7&_nc_ohc=UBMMC4soiEwAX-4i4DV&_nc_ht=scontent.fpnk3-1.fna&oh=b62f1f3454f65fc220a0aa92db08be58&oe=61448C2C"
}

### Payment
POST http://localhost:5000/users/payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjM1ZDc4ZmIzZjRhMTY1NDE0NTllNCIsImlhdCI6MTYyOTk0MDk5NCwiZXhwIjoxNjMyNTMyOTk0fQ.2kfN3s0gNcoPScqZ91VWw2-zYCkhPI3OCbJd7hnIteI

{
    "orderId": "12345",
    "amount": 50000,
    "firstName": "Abdur",
    "lastName": "Rahim",
    "email": "abdoerrahiem@gmail.com",
    "phone": "089694624299"
}

### Update status user
PUT http://localhost:5000/users/update/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjM1ZDc4ZmIzZjRhMTY1NDE0NTllNCIsImlhdCI6MTYyOTk0MDk5NCwiZXhwIjoxNjMyNTMyOTk0fQ.2kfN3s0gNcoPScqZ91VWw2-zYCkhPI3OCbJd7hnIteI


### Payment success
GET http://localhost:5000/payment/success

### Payment failed
GET http://localhost:5000/payment/failed


// Jobs
### Get jobs
GET http://localhost:5000/jobs

### Get job
GET http://localhost:5000/jobs/6120dafed46efa149447d948


// Application
### Create application
POST http://localhost:5000/applications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBiYjE3OTE2MTc1MTdiMDE5YzRjMiIsImlhdCI6MTYyOTYxNjI3OCwiZXhwIjoxNjMyMjA4Mjc4fQ.gJ_8oHYOPGz9Km2gKOZGBwm8H299A6p8VJKM4S1dYCE

{
    "phone": "+6289694624299",
    "appLetter": "Hi, I am interested",
    "location": "Mempawah, Indonesia",
    "resume": "https://res.cloudinary.com/abdoerrahiem/image/upload/v1629616471/jobfinder/My_Resume_yr3cie.pdf",
    "jobId": "6120dafed46efa149447d955",
    "status": "review"
}

### Get my applications
GET http://localhost:5000/applications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjM1ZDc4ZmIzZjRhMTY1NDE0NTllNCIsImlhdCI6MTYyOTkzNjkxNCwiZXhwIjoxNjMyNTI4OTE0fQ.vfvhp_IZUtnMhDQs85Pt63O1YymLrD7WsymSlCbKL2w

### Get application
GET http://localhost:5000/applications/6121fb05691836111cf3c15f

### Update application
PUT http://localhost:5000/applications/61266c1349ead90004e4aeea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjM1ZDc4ZmIzZjRhMTY1NDE0NTllNCIsImlhdCI6MTYyOTkzNjkxNCwiZXhwIjoxNjMyNTI4OTE0fQ.vfvhp_IZUtnMhDQs85Pt63O1YymLrD7WsymSlCbKL2w

{
    "status": "interview"
}


// Notifications
### Get my notifications
GET http://localhost:5000/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBiYjE3OTE2MTc1MTdiMDE5YzRjMiIsImlhdCI6MTYyOTYxNjI3OCwiZXhwIjoxNjMyMjA4Mjc4fQ.gJ_8oHYOPGz9Km2gKOZGBwm8H299A6p8VJKM4S1dYCE

### Update notification
PUT http://localhost:5000/notifications/6122021357f4101750e67ccb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjBiYjE3OTE2MTc1MTdiMDE5YzRjMiIsImlhdCI6MTYyOTYxNjI3OCwiZXhwIjoxNjMyMjA4Mjc4fQ.gJ_8oHYOPGz9Km2gKOZGBwm8H299A6p8VJKM4S1dYCE


// Conversation
### Create conversation
POST http://localhost:5000/conversations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjc0ZDQwNzAxYjk5MjE1ODdmYWM1MSIsImlhdCI6MTYzMDM3MjQ3NiwiZXhwIjoxNjMyOTY0NDc2fQ.BocevLN5ungLXTNWXCsvmmNgP6lhxmSky9CGRLrDQEM

{
    "member": "6129e8bff36e2000041127b0"
}

### Get my conversations
GET http://localhost:5000/conversations/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjhkOTEzZTljMjc0MDAwNGIzZDUwMSIsImlhdCI6MTYzMDM3MzU4OCwiZXhwIjoxNjMyOTY1NTg4fQ.RYTvToL9RfC3hJQ0A72GEMxzRQyrLii7quO5azwkg5s

// Message
### Create message
POST http://localhost:5000/messages/612d82d61c6867170c46ba59
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjhkOTEzZTljMjc0MDAwNGIzZDUwMSIsImlhdCI6MTYzMDM3NDA4OCwiZXhwIjoxNjMyOTY2MDg4fQ.-Y6Wxz6vAV_3TfdtsSQHQyq57YeYsu0CH0xszsHA0gY

{
    "receiver": "61274d40701b9921587fac51",
    "text": "I'm good, you?"
}

### get messages by conversation id
GET http://localhost:5000/messages/612d82d61c6867170c46ba59
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMjhkOTEzZTljMjc0MDAwNGIzZDUwMSIsImlhdCI6MTYzMDM3NDA4OCwiZXhwIjoxNjMyOTY2MDg4fQ.-Y6Wxz6vAV_3TfdtsSQHQyq57YeYsu0CH0xszsHA0gY

####
POST https://fcm.googleapis.com/fcm/send
Content-Type:application/json
Authorization: key=AAAA4edFhXY:APA91bHYyxJNTU8Hp2pP3yW9IYWPXg_-A9BEXV3ua1kvfk4c-R7ayNsaN_CF10AzsoDuKjHDCLSpxRU3zh3UmJFgOs4ABOwFCJ3e44zWfy22KiIuuENxIAh9AdUOiM1D1MTlbUgptdwv

{
  "to": "deV8BdJnQ5GTAr34RfcHrv:APA91bGotM-r97Xwsdh_4h0NQ-bADo3yC-ivmiLEdKgKF5T3kpvWOndSMGG2A0KNosNkaqNAkve2wIXsYTGpQGJxyvlsEK8xxum7JLNAYzL357uvupJmOgSrRVkZLWqho5wpg51AwP9x",
  "notification": {
      "body": "Hello",
      "title": "Title",
      "image": "https://img.okezone.com/content/2021/09/01/45/2464287/resmi-gabung-manchester-united-unggah-foto-cristiano-ronaldo-pakai-jersey-kandang-WhMFKsW1QR.jpg",
      "actions": [
          {"title": "Like"},
          {"title": "Comment"}
      ]
  },
  "data": {
      "type": "phone",
  }
}



